### ISSUE TITLE
setting an array element with a sequence.

### ISSUE THREAD

**Issue by sherlockhoatszx** [lc222/HAN-text-classification-tf#1]
Hi got an error that 
tf 1.1 version
Traceback (most recent call last):
  File "train.py", line 119, in <module>
    step = train_step(x, y)
  File "train.py", line 92, in train_step
    _, step, summaries, cost, accuracy = sess.run([train_op, global_step, train_summary_op, loss, acc], feed_dict)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 968, in _run
    np_val = np.asarray(subfeed_val, dtype=subfeed_dtype)
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/numeric.py", line 531, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: setting an array element with a sequence.

**Comment by sherlockhoatszx** [comment]
and i have used the np.array after the append and convert the labels to np.array

**Comment by sherlockhoatszx** [comment]
looks like you did not import this comment'''将所有的评论文件都转化为30*30的索引矩阵，也就是每篇都有30个句子，每个句子有30个单词
不够的补零，多余的删除，并保存到最终的数据集文件之中‘’‘ right.

batch function do this padding in the data load file, but not used in the train or datautils , maybe you use the batch padding offline somewhere and save it .

**Comment by sherlockhoatszx** [comment]
I amend this code in the DataUtils, and got it run

```
data_x = []

max_sent_in_doc = 30
max_word_in_sent = 30
for perdoc in x_text:
    doc2idx = []
    snt_doc = perdoc.split('。')
    for i,sent in enumerate(snt_doc):
        if i <max_sent_in_doc:
            word2idx =[]
            for j,word in enumerate(sent.split(' ')):
                if j < max_word_in_sent:
                    word2idx.append(np.array(vocab.get(word,UNKNOWN)))
            npad = (0,30-len(word2idx))

            #add padding 
            word2idx = np.pad(word2idx, pad_width=npad, mode='constant', constant_values=0)#padding
            doc2idx.append(np.array(word2idx))
    npad2 =((0,30-len(doc2idx)),(0,0))

    #add padding
    doc2idx = np.pad(doc2idx, pad_width=npad2, mode='constant', constant_values=0)#padding
    data_x.append(np.array(doc2idx))
```

**Comment by lc222** [comment]
yes, there is a bug here. I forget to pad the input data, Thank you. I'll add this soon

**Comment by pmm-511** [comment]
请问数据预处理该怎么改，博客里写的还是错的，求教
